version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
       - "9092:9092"
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  influxdb:
    image: influxdb
    restart: always
    volumes:
      - ${PWD}/influxdb.conf:/etc/influxdb/influxdb.conf
      - /var/lib/influxdb/data
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
  grafana:
    image: grafana/grafana
    restart: always
    links:
      - influxdb:influxdb
    ports:
      - "3000:3000"